### ISSUE TITLE
Question on DNS Hijacking

### ISSUE THREAD

**Issue by JeremyRand** [mk-fg/convergence#7]
The readme says:

"Send IP along with hostname (for e.g. SNI and cert validation) and port, because same name can be resolved to different hosts in case of CDNs or round-robin-dns mirrors, which can have unrelated certificates."

From glancing at the server code, it looks like if an IP is received from the end user, the server connects to that IP (I could be misreading though).  Does this introduce security problems if the end user's DNS has been hijacked by the same attacker that is doing a MITM attack?

**Comment by mk-fg** [comment]
Maybe I'm not understanding exact attack steps (can you walk me through it, maybe?), but don't see how it would.

Whatever the DNS is, user is connecting to endpoint X and asking what's the cert for the X is, with the assertion that IP/DNS-name (for SNI) is enough to unambiguously identify same endpoint from any notary as well as from user's machine.

If that assertion fails, and it's some random Malory for the user, they get different cert (assuming that Malory doesn't have endpoint X private key), and user is alerted.

Only hostname (whether it's "correct" or not, for whatever definition of "correct") isn't enough to identify enpoint X, because any site can have any number of addresses, each with a different TLS cert.

**Comment by JeremyRand** [comment]
Let's say that Alice types www.google.com into her browser.  Google has 2 legitimate IP addresses, A and B.  Mallory intercepts the DNS requests from Alice so that Alice receives IP address C for Google, which is not really under Google's control, but actually under Mallory's control.  Now Alice asks her notary servers to check the certificate that IP address C has when the SNI is set to www.google.com.  The notaries check this, and correctly report Mallory's cert, which matches what Alice sees, so Alice's browser doesn't show any errors, even though IP address C is not controlled by Google and is actually controlled by Mallory doing a MITM between Alice and Google.

Does this attack work, or am I missing something?

**Comment by mk-fg** [comment]
Thanks for detailed explaination.

Yeah, I think the attack you described should totally work, being indistinguishable from the usual "google rack in your ISP with their own certs" scenario from the addon's viewpoint.

**Comment by mk-fg** [comment]
I should probably also mention that above attack only applies to purely perspectives-based pki.

Server code here also has the usual "bundle of certs" pki plugin, to which this scenario doesn't really apply.

Maybe there should also be a notary plugin that checks simple DNS A round-robin pool (from its perspective) for the specified IP and raises alarm if it's not there.
Would fail for some CDNs, but might work for most other random sites on the net.

**Comment by JeremyRand** [comment]
Makes sense.  Yeah, a notary plugin for checking the round-robin pool would fix the security issue, and hopefully wouldn't break too many sites.  It could also be combined with the old behavior of the notary directly connecting to the hostname.  So the notary would only report failure if the website is using different certs per IP _and_ the IP doesn't show up in the round-robin pool.

**Comment by mk-fg** [comment]
It actually breaks quite a lot.

Just from this thread - google.com and all google sites (youtube, etc) and APIs (fonts, js libs like jquery, etc).
And github.com itself, from two different machines: https://ezcrypt.it/pyAn#S2cf6e0KVUBFhapTEyO6r1W0

So I'd say it's more the case that "nothing big works, only false-positives", which is kinda useless.

**Comment by mk-fg** [comment]
Though github likely has same cert across both IPs, unlike google, so that can be handled correctly.
